services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Services\Domain\Database\Api\ConnectionInterface:
    class: Services\Domain\Database\Service\Connection

  Services\Domain\Database\Api\ParamsInterface:
    class: Services\Domain\Database\Service\Params