parameters:
  app.name: console-application
  app.version: '1.0.0'

imports:
  - {resource: ../src/*/config/services.yaml}

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
