services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Services\Infrastructure\Console\Api\CommandHandlerInterface:
    class: Services\Infrastructure\Console\Service\CommandHandler